/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as ShoppingTripRouteImport } from './routes/shopping-trip'
import { Route as GroceryListRouteImport } from './routes/grocery-list'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingTripRoute = ShoppingTripRouteImport.update({
  id: '/shopping-trip',
  path: '/shopping-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryListRoute = GroceryListRouteImport.update({
  id: '/grocery-list',
  path: '/grocery-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/grocery-list': typeof GroceryListRoute
  '/shopping-trip': typeof ShoppingTripRoute
  '/stores': typeof StoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/grocery-list': typeof GroceryListRoute
  '/shopping-trip': typeof ShoppingTripRoute
  '/stores': typeof StoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/grocery-list': typeof GroceryListRoute
  '/shopping-trip': typeof ShoppingTripRoute
  '/stores': typeof StoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/grocery-list'
    | '/shopping-trip'
    | '/stores'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/chat' | '/grocery-list' | '/shopping-trip' | '/stores'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/grocery-list'
    | '/shopping-trip'
    | '/stores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  GroceryListRoute: typeof GroceryListRoute
  ShoppingTripRoute: typeof ShoppingTripRoute
  StoresRoute: typeof StoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-trip': {
      id: '/shopping-trip'
      path: '/shopping-trip'
      fullPath: '/shopping-trip'
      preLoaderRoute: typeof ShoppingTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery-list': {
      id: '/grocery-list'
      path: '/grocery-list'
      fullPath: '/grocery-list'
      preLoaderRoute: typeof GroceryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  GroceryListRoute: GroceryListRoute,
  ShoppingTripRoute: ShoppingTripRoute,
  StoresRoute: StoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
